import {useEffect, useRef, useState, type FormEvent} from 'react';
import {Link, useNavigate, useParams} from 'react-router-dom';
import {BellOff, Search, ExternalLink, ArrowUpRight, ShieldCheck, X, CarFront} from 'lucide-react';
import {api, post, patch, useGet, time, date, type Camera, type Observation} from './api';
import {Badge, Empty, ErrorState, Loading, Plate, Modal, useAction, notice} from './ui';
import MapView from './MapView';
import JevAssistant from './JevAssistant';
import {createPortal} from 'react-dom';
import ReviewScore,{ReviewWarning} from './ReviewScore';

export function NotificationControls({subject}:{subject:string}) {
 const user=useGet<any>('/auth/me'), q=useGet<any>('/notification-preferences?subject='+encodeURIComponent(subject));
 const action=useAction(); const [value,setValue]=useState('');
 const change=async (v:string)=>{setValue(v);if(!v)return;const [kind,duration]=v.split(':');
   await action(()=>post('/notification-preferences',{subject,action:kind,minutes:duration?Number(duration):null}),kind==='dismiss'?'Existing alerts dismissed':'Notification preference saved');setValue('');};
 return <div className="notification-control"><BellOff size={15}/><select aria-label="Vehicle alert controls" value={value} onChange={e=>change(e.target.value)}>
  <option value="">{q.data?.stopped?'Alerts stopped':q.data?.muted?'Vehicle muted':'Vehicle alert controls'}</option>
  <option value="mute:15">Mute for 15 minutes</option><option value="mute:60">Mute for one hour</option><option value="mute">Mute until unmuted</option>
  <option value="unmute">Unmute for me</option><option value="dismiss">Dismiss existing alerts</option>
  {user.data?.role==='admin'&&<><option value="stop">Stop alerts for everyone</option><option value="enable">Re-enable alerts for everyone</option></>}
 </select>{q.data?.muted&&<span className="muted">{q.data.until?'Until '+time(q.data.until)+' IST':'Until re-enabled'}</span>}</div>
}

export function NotificationBanners(){
 const [soundHost,setSoundHost]=useState<HTMLElement|null>(null);
 useEffect(()=>setSoundHost(document.getElementById('notification-sound-control')),[]);
 const [items,setItems]=useState<any[]>([]),[sound,setSound]=useState(()=>localStorage.getItem('sylrak:sound')==='true');
 useEffect(()=>{let stopped=false,busy=false;const poll=async()=>{if(busy)return;busy=true;try{const data=await post('/notifications/poll',{});
  if(!stopped&&data.items.length){setItems(old=>[...old,...data.items].slice(-3));
   if(sound){const Audio=(window as any).AudioContext;if(Audio){const ctx=new Audio();const osc=ctx.createOscillator(),gain=ctx.createGain();gain.gain.value=.03;osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=550;osc.start();osc.stop(ctx.currentTime+.12);osc.onended=()=>ctx.close();}}}
 }catch{}finally{busy=false}};poll();const t=setInterval(poll,2000);return()=>{stopped=true;clearInterval(t)}},[sound]);
 useEffect(()=>{if(!items.length)return;const t=setTimeout(()=>setItems([]),10000);return()=>clearTimeout(t)},[items]);
 return <>{soundHost&&createPortal(<label className="sound-setting"><input type="checkbox" checked={sound} onChange={e=>{setSound(e.target.checked);localStorage.setItem('sylrak:sound',String(e.target.checked))}}/>Alert sound</label>,soundHost)}<div className="notification-stack" aria-live="polite">{items.map(a=><article key={a.id} className={'notification-banner '+a.priority}><strong>{a.priority.toUpperCase()}</strong><p>{a.message}</p><Link to="/alerts">Review alerts</Link><button className="icon-btn" aria-label="Dismiss alert banner" onClick={()=>setItems(old=>old.filter(x=>x.id!==a.id))}><X size={15}/></button></article>)}</div></>
}

export function RegistrationPage(){
 const [input,setInput]=useState(''),[plate,setPlate]=useState('');const q=useGet<any>('/registrations/'+encodeURIComponent(plate),!!plate);
 const search=(e:FormEvent)=>{e.preventDefault();setPlate(input.trim())};
 return <div className="page-content registration-page"><div className="section-intro"><div><h2>Registration lookup</h2><p>Basic registration information. Camera sightings are not required.</p></div><Badge>Offline demonstration registry</Badge></div>
 <form className="panel lookup-form" onSubmit={search}><label>Registration number<input value={input} onChange={e=>setInput(e.target.value)} placeholder="DL10CZ7788" aria-label="Registration lookup number" required/></label><button className="primary"><Search size={16}/>Look up registration</button></form>
 <div className="example-row">Try a vehicle with no sightings: <button className="text-button mono" onClick={()=>{setInput('DL10CZ7788');setPlate('DL10CZ7788')}}>DL10CZ7788</button></div>
 {plate&&(q.isLoading?<Loading/>:q.isError?<ErrorState error={q.error} retry={()=>q.refetch()}/>:q.data&&<section className="panel registration-result"><div className="section-intro"><Plate value={q.data.plate}/><Badge tone="amber">{q.data.record?'Demonstration registration record':'Live lookup unavailable'}</Badge></div>
 {q.data.record?<dl className="record-grid">{Object.entries(q.data.record).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v??'Unavailable')}</dd></div>)}</dl>:<Empty title="No record available">{q.data.message}</Empty>}
 <p className="muted">Source: {q.data.source} · Updated {q.data.updated_at}. These synthetic records do not verify a real registration.</p></section>)}
 <div className="panel official-lookup"><ShieldCheck size={21}/><div><h3>Real registration enquiry</h3><p>Use the official service. Live vehicle-data access is not connected to this prototype.</p></div><a className="secondary" href="https://parivahan.gov.in/parivahan/en/content/license-registration-details" target="_blank" rel="noreferrer">Open official Parivahan lookup <ExternalLink size={15}/></a></div></div>
}

const COLORS=['white','silver','black','blue','red','green','yellow','grey'];
const empty={colors:[] as string[],color_mode:'all',regions:{} as Record<string,string>,features:[] as string[],pattern:'',visibility:'',plate_visibility:'',make_model:'',vehicle_type:'car',camera_ids:[] as string[],run_id:'current',include_unknown:true};
function CandidateVisual({item}:{item:any}){
 const o=item.observation,a=item.explanation?.appearance||o.details?.appearance;
 return o.evidence?.vehicle_url?<img className="candidate-image" src={o.evidence.vehicle_url} alt="Stored vehicle evidence"/>:<div className="candidate-placeholder"><CarFront size={38}/><span>Photographic evidence unavailable</span>{a?.colors?.length>0&&<div className="color-swatches">{a.colors.map((c:string)=><i key={c} style={{background:c}} title={c}/>)}</div>}</div>
}
export function AppearancePage({cameras,onEvidence}:{cameras:Camera[];onEvidence:(o:Observation)=>void}){
 const [form,setForm]=useState({...empty}),[features,setFeatures]=useState(''),[region,setRegion]=useState(''),[regionColor,setRegionColor]=useState('black');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState(false);
 const [caseId,setCaseId]=useState(''),[caseName,setCaseName]=useState('Vehicle appearance enquiry');const cases=useGet<any[]>('/cases');const action=useAction(),navigate=useNavigate();
 const scrollToJevResults=useRef(false);
 useEffect(()=>{if(result&&scrollToJevResults.current){scrollToJevResults.current=false;requestAnimationFrame(()=>{const target=document.getElementById('appearance-results');target?.focus({preventScroll:true});target?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})})}},[result]);
 const query=()=>({...form,features:features.split(',').map(x=>x.trim()).filter(Boolean),regions:region?{[region]:regionColor}:{},from_time:from?Date.parse(from+'+05:30')/1000:null,to_time:to?Date.parse(to+'+05:30')/1000:null});
 const run=async(q:any)=>{setBusy(true);setSelected([]);setResult(null);try{setResult(await post('/search/candidates',q));return true}catch(e){notice((e as Error).message,true);return false}finally{setBusy(false)}};
 const searchWithJev=async(f:any)=>{scrollToJevResults.current=true;const next={...empty,...f,vehicle_type:f.vehicle_type||'',camera_ids:form.camera_ids,run_id:form.run_id,include_unknown:form.include_unknown};setForm(next);setFeatures((f.features||[]).join(', '));const r=Object.entries(f.regions||{})[0];setRegion(r?.[0]||'');if(r)setRegionColor(String(r[1]));const ok=await run({...next,from_time:from?Date.parse(from+'+05:30')/1000:null,to_time:to?Date.parse(to+'+05:30')/1000:null});if(!ok)throw new Error('Filters were applied, but the search failed. Check the local connection and click Find candidates to retry without another Jev request.');};
 const demo=(kind:string)=>{const q={...empty,colors:kind==='covered'?['blue']:['white'],make_model:kind==='common'?'Dzire':'',pattern:kind==='distinctive'?'contrasting panel':'',visibility:kind==='covered'?'heavily obscured':'',plate_visibility:kind==='common'?'visibly absent':'',include_unknown:false};setForm(q);setFeatures('');setRegion('');setFrom('');setTo('');run(q)};
 const chosen=result?.items.filter((x:any)=>selected.includes(x.id))||[];
 const create=async()=>{const ids=chosen.map((x:any)=>x.observation.id);if(!ids.length){notice('Select at least one candidate.',true);return}
  if(caseId){for(const id of ids)await action(()=>post('/cases/'+caseId+'/links',{observation_id:id}));navigate('/cases/'+caseId)}else{const c=await action(()=>post('/cases',{title:caseName,observation_ids:ids,criteria:query()}));if(c)navigate('/cases/'+c.id)}};
 return <div className="page-content"><div className="section-intro"><div><Link className="back-link" to="/investigations">← Vehicle search</Link><h2>Search distinctive appearance</h2><p>Find candidates using what is visible. Similar appearance does not establish identity.</p></div><Link className="secondary" to="/cases">Case workspace <ArrowUpRight size={15}/></Link></div>
 <JevAssistant onSearch={searchWithJev}/>
 <form className="panel appearance-form" onSubmit={e=>{e.preventDefault();run(query())}}>
 <div className="filter-grid"><label>Vehicle type<select value={form.vehicle_type} onChange={e=>setForm({...form,vehicle_type:e.target.value})}><option value="">Any type</option>{['car','motorcycle','bus','truck'].map(t=><option key={t}>{t}</option>)}</select></label><label>Make / model<input aria-label="Appearance model" value={form.make_model} onChange={e=>setForm({...form,make_model:e.target.value})} placeholder="e.g. Maruti Suzuki Dzire"/></label><label>Pattern<select value={form.pattern} onChange={e=>setForm({...form,pattern:e.target.value})}><option value="">Any pattern</option>{['solid','two-tone','stripes','graphics','contrasting panel'].map(x=><option key={x}>{x}</option>)}</select></label><label>Visibility<select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="">Any visibility</option>{['clear','partly obscured','heavily obscured'].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <div className="color-selector"><span>Observed colors</span>{COLORS.map(c=><button key={c} type="button" aria-pressed={form.colors.includes(c)} onClick={()=>setForm({...form,colors:form.colors.includes(c)?form.colors.filter(x=>x!==c):[...form.colors,c]})}><i style={{background:c}}/>{c}</button>)}<select aria-label="Color match mode" value={form.color_mode} onChange={e=>setForm({...form,color_mode:e.target.value})}><option value="all">All selected</option><option value="any">Any selected</option></select></div>
 <details><summary>Distinctive details and search area</summary><div className="filter-grid"><label>Visible features<input value={features} onChange={e=>setFeatures(e.target.value)} placeholder="roof rack, left bumper dent"/></label><label>Body region<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">Any region</option>{['body','roof','bonnet','doors'].map(x=><option key={x}>{x}</option>)}</select></label><label>Region color<select value={regionColor} onChange={e=>setRegionColor(e.target.value)}>{COLORS.map(x=><option key={x}>{x}</option>)}</select></label><label>Plate visibility<select value={form.plate_visibility} onChange={e=>setForm({...form,plate_visibility:e.target.value})}><option value="">Any plate visibility</option>{['readable','unreadable','obscured','out of view','visibly absent','unknown'].map(x=><option key={x}>{x}</option>)}</select></label><label>From · IST<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Until · IST<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Camera area<select value={form.camera_ids[0]||''} onChange={e=>setForm({...form,camera_ids:e.target.value?[e.target.value]:[]})}><option value="">All monitored cameras</option>{cameras.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</select></label><label>History<select value={form.run_id} onChange={e=>setForm({...form,run_id:e.target.value})}><option value="current">Current run</option><option value="all">All stored runs</option></select></label><label className="checkbox-label"><input type="checkbox" checked={form.include_unknown} onChange={e=>setForm({...form,include_unknown:e.target.checked})}/>Include unknown attributes</label></div></details>
 <div className="search-footer"><button className="primary" disabled={busy}><Search size={16}/>{busy?'Searching…':'Find candidates'}</button><span>Demonstrations:</span><button className="secondary" type="button" onClick={()=>demo('distinctive')}>Multicolor car</button><button className="secondary" type="button" onClick={()=>demo('common')}>White Dzires</button><button className="secondary" type="button" onClick={()=>demo('covered')}>Covered vehicles</button></div></form>
 {result&&<><div id="appearance-results" tabIndex={-1} aria-label="Appearance search results"><ReviewWarning/></div><div className="section-intro"><p>Showing {result.items.length} of {result.total} candidates · Best description matches first; review score breaks ties. Unknown attributes remain labeled.</p><button className="secondary" disabled={selected.length<2} onClick={()=>setCompare(true)}>Compare selected ({selected.length})</button></div>
 {!!selected.length&&<div className="panel selection-bar"><label>Add to case<select value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Create new case</option>{cases.data?.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{!caseId&&<label>Case title<input value={caseName} onChange={e=>setCaseName(e.target.value)}/></label>}<button className="primary" onClick={create}>Add {selected.length} candidates</button></div>}
 <div className="candidate-grid">{result.items.map((item:any)=><article className="panel candidate-card" key={item.id}><label className="candidate-select"><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>setSelected(old=>old.includes(item.id)?old.filter(x=>x!==item.id):[...old,item.id].slice(-4))}/>Compare / add to case</label><CandidateVisual item={item}/><div className="candidate-body"><span className="match-ranking">Description match {item.explanation.match_score}/100</span><Plate value={item.observation.plate} small/><h3>{item.observation.details?.make_model||'Unknown model'}</h3><p>{item.observation.camera.name} · {time(item.last_seen)} IST</p><Badge>{item.explanation.appearance.origin}</Badge><p className="match-text">Matches: {item.explanation.matches.join(' · ')||'None established'}</p>{!!item.explanation.conflicts.length&&<p className="conflict-text">Contradictions: {item.explanation.conflicts.join(' · ')}</p>}{!!item.explanation.unknown.length&&<p className="muted">Unknown: {item.explanation.unknown.join(' · ')}</p>}<ReviewScore value={item.theft_review}/><div className="card-actions"><button className="secondary" onClick={()=>onEvidence(item.observation)}>Inspect sighting</button>{item.observation.vehicle_id&&item.observation.status==='accepted'&&<Link className="text-button" to={'/vehicles/'+item.observation.vehicle_id+'?run='+item.observation.run_id}>History ({item.sightings})</Link>}</div></div></article>)}</div>{!result.items.length&&<Empty title="No candidates in this selection">Widen the camera or time selection.</Empty>}</>}
 {compare&&<Modal open wide title="Compare visible evidence" onClose={()=>setCompare(false)}><div className="comparison-grid">{chosen.map((item:any)=><article key={item.id}><CandidateVisual item={item}/><h3>{item.observation.details?.make_model||'Unknown'}</h3><p>{item.observation.camera.name} · {time(item.last_seen)}</p><p>{item.explanation.matches.join(' · ')||'No shared details established'}</p><p className="muted">Unknown: {item.explanation.unknown.join(', ')||'None of the requested details'}</p><p className="conflict-text">Contradictions: {item.explanation.conflicts.join(', ')||'None observed'}</p></article>)}</div><p className="muted">Matching descriptions alone do not establish that these are the same vehicle.</p></Modal>}
 </div>
}

export function CasesPage(){const q=useGet<any[]>('/cases');return <div className="page-content"><div className="section-intro"><div><h2>Investigation cases</h2><p>Keep possible connections separate from accepted vehicle histories.</p></div><Link className="primary" to="/appearance">Find candidates</Link></div>{!q.data?<Loading/>:!q.data.length?<Empty title="No cases yet">Select candidates in appearance search to create a case.</Empty>:<div className="case-list">{q.data.map(c=><Link className="panel case-list-row" key={c.id} to={'/cases/'+c.id}><div><h3>{c.title}</h3><p>{date(c.created_at)} · {c.created_by}</p></div><ArrowUpRight size={18}/></Link>)}</div>}</div>}

export function CasePage({cameras,onEvidence}:{cameras:Camera[];onEvidence:(o:Observation)=>void}){
 const {id}=useParams();const q=useGet<any>('/cases/'+id);const [tab,setTab]=useState('Candidates'),[proposed,setProposed]=useState(false),[review,setReview]=useState<any>(null),[reason,setReason]=useState(''),[selected,setSelected]=useState<string|undefined>();const action=useAction();
 if(q.isError)return <ErrorState error={q.error} retry={()=>q.refetch()}/>;if(!q.data)return <Loading/>;const c=q.data;
 const visible=c.links.filter((l:any)=>l.observation&&l.status===(proposed?'proposed':'accepted'));const observations=visible.map((l:any)=>({...l.observation,status:'accepted'}));
 const reviewNow=async()=>{const result=await action(()=>patch('/cases/'+id+'/links/'+review.id,{status:review.next,reason}),'Case decision recorded');if(result){setReview(null);setReason('')}};
 return <div className="page-content"><div className="section-intro"><div><Link className="back-link" to="/cases">← Cases</Link><h2>{c.title}</h2><p>Case {c.id.slice(0,8)} · Review decisions do not rewrite original recognition.</p></div><Link className="secondary" to="/appearance">Add candidates</Link></div><div className="search-mode-tabs">{['Candidates','Journey','Evidence','Full case details'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {(tab==='Journey'||tab==='Full case details')&&<section className="panel case-map"><div className="section-intro"><h3>{proposed?'Proposed connections':'Operator-accepted case sightings'}</h3><label className="checkbox-label"><input type="checkbox" checked={proposed} onChange={e=>setProposed(e.target.checked)}/>Show proposed connections</label></div><MapView cameras={cameras} observations={observations} selectedCamera={selected} onCamera={setSelected} connectionColor={proposed?'#d5a448':'#7aacfa'}/><p className="muted">Estimated connections between observed cameras. {proposed?'Identity is not established.':'Operator-reviewed case hypothesis; not an exact plate match.'}</p></section>}
 {(tab==='Candidates'||tab==='Evidence'||tab==='Full case details')&&<div className="case-list">{c.links.map((l:any)=><article className="panel case-candidate" key={l.id}><div className="section-intro"><h3>{l.observation?.details?.make_model||'Unknown vehicle'}</h3><Badge tone={l.status==='accepted'?'blue':l.status==='proposed'?'amber':'neutral'}>{l.status}</Badge></div>{l.observation?<><p>{l.observation.camera.name} · {date(l.observation.observed_at)} {time(l.observation.observed_at,true)} IST</p><p>Observed: {l.observation.details?.appearance?.colors?.join(', ')||l.observation.color} · {l.observation.details?.appearance?.visibility||'Visibility unknown'}</p><div className="card-actions"><button className="secondary" onClick={()=>onEvidence(l.observation)}>Inspect original evidence</button><NotificationControls subject={'observation:'+l.observation.id}/></div></>:<p>Observation expired under the retention policy.</p>}<div className="card-actions">{['accepted','rejected','proposed'].filter(x=>x!==l.status).map(status=><button className="text-button" key={status} onClick={()=>{setReview({...l,next:status});setReason('')}}>{status==='accepted'?'Accept case connection':status==='rejected'?'Reject candidate':'Reverse to proposed'}</button>)}</div><details><summary>Review history ({l.history.length})</summary>{l.history.map((h:any,i:number)=><p key={i}>{h.action} · {h.actor} · {date(h.at)} {time(h.at)} — {h.reason}</p>)}</details></article>)}</div>}
 {tab==='Journey'&&<div className="panel case-candidate">{visible.length?visible.map((l:any)=><button className="timeline-case-row" key={l.id} onClick={()=>{setSelected(l.observation.camera_id);onEvidence(l.observation)}}><span>{time(l.observation.observed_at,true)}</span><strong>{l.observation.camera.name}</strong><span>{l.status}</span></button>):<Empty title="No sightings in this layer">Review candidates, or switch to proposed connections.</Empty>}</div>}
 {(tab==='Full case details'||tab==='Candidates')&&<section className="panel case-candidate"><h3>Appearance watch</h3><p>Administrator only. Requires a camera area, time window, and distinguishing feature from the saved search.</p><button className="secondary" onClick={()=>action(()=>post('/cases/'+id+'/watch',{criteria:c.criteria,hours:1}),'Appearance watch enabled for one hour')}>Enable one-hour review alerts</button><p className="muted">{c.watches.length} saved watch rules. Appearance leads remain medium-priority review items.</p>{c.watches.filter((w:any)=>w.active&&w.expires_at*1000>Date.now()).map((w:any)=><button key={w.id} className="text-button" onClick={()=>action(()=>api('/cases/'+id+'/watch/'+w.id,{method:'DELETE'}),'Appearance watch stopped')}>Stop watch · expires {time(w.expires_at)}</button>)}</section>}
 {review&&<Modal open title="Record an evidence-based decision" onClose={()=>setReview(null)}><p>This changes the case connection only. It does not confirm stolen status.</p><label>Reason<textarea aria-label="Case review reason" value={reason} onChange={e=>setReason(e.target.value)} minLength={5}/></label><button className="primary" disabled={reason.trim().length<5} onClick={reviewNow}>Save {review.next} decision</button></Modal>}
 </div>
}
